### YamlMime:ManagedReference
items:
- uid: TinyGiantStudio.Text.AssetSettings.MeshExportStyle
  commentId: T:TinyGiantStudio.Text.AssetSettings.MeshExportStyle
  id: AssetSettings.MeshExportStyle
  parent: TinyGiantStudio.Text
  children:
  - TinyGiantStudio.Text.AssetSettings.MeshExportStyle.exportAsMeshAsset
  - TinyGiantStudio.Text.AssetSettings.MeshExportStyle.exportAsObj
  langs:
  - csharp
  - vb
  name: AssetSettings.MeshExportStyle
  nameWithType: AssetSettings.MeshExportStyle
  fullName: TinyGiantStudio.Text.AssetSettings.MeshExportStyle
  type: Enum
  source:
    remote:
      path: Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
      branch: main
      repo: https://github.com/Rocketshift-Studio/Trophy.git
    id: MeshExportStyle
    path: ../Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
    startLine: 81
  assemblies:
  - Assembly-CSharp-firstpass
  namespace: TinyGiantStudio.Text
  syntax:
    content: public enum AssetSettings.MeshExportStyle
    content.vb: Public Enum AssetSettings.MeshExportStyle
- uid: TinyGiantStudio.Text.AssetSettings.MeshExportStyle.exportAsObj
  commentId: F:TinyGiantStudio.Text.AssetSettings.MeshExportStyle.exportAsObj
  id: exportAsObj
  parent: TinyGiantStudio.Text.AssetSettings.MeshExportStyle
  langs:
  - csharp
  - vb
  name: exportAsObj
  nameWithType: AssetSettings.MeshExportStyle.exportAsObj
  fullName: TinyGiantStudio.Text.AssetSettings.MeshExportStyle.exportAsObj
  type: Field
  source:
    remote:
      path: Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
      branch: main
      repo: https://github.com/Rocketshift-Studio/Trophy.git
    id: exportAsObj
    path: ../Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
    startLine: 83
  assemblies:
  - Assembly-CSharp-firstpass
  namespace: TinyGiantStudio.Text
  syntax:
    content: exportAsObj = 0
    return:
      type: TinyGiantStudio.Text.AssetSettings.MeshExportStyle
- uid: TinyGiantStudio.Text.AssetSettings.MeshExportStyle.exportAsMeshAsset
  commentId: F:TinyGiantStudio.Text.AssetSettings.MeshExportStyle.exportAsMeshAsset
  id: exportAsMeshAsset
  parent: TinyGiantStudio.Text.AssetSettings.MeshExportStyle
  langs:
  - csharp
  - vb
  name: exportAsMeshAsset
  nameWithType: AssetSettings.MeshExportStyle.exportAsMeshAsset
  fullName: TinyGiantStudio.Text.AssetSettings.MeshExportStyle.exportAsMeshAsset
  type: Field
  source:
    remote:
      path: Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
      branch: main
      repo: https://github.com/Rocketshift-Studio/Trophy.git
    id: exportAsMeshAsset
    path: ../Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
    startLine: 84
  assemblies:
  - Assembly-CSharp-firstpass
  namespace: TinyGiantStudio.Text
  syntax:
    content: exportAsMeshAsset = 1
    return:
      type: TinyGiantStudio.Text.AssetSettings.MeshExportStyle
references:
- uid: TinyGiantStudio.Text
  commentId: N:TinyGiantStudio.Text
  href: TinyGiantStudio.html
  name: TinyGiantStudio.Text
  nameWithType: TinyGiantStudio.Text
  fullName: TinyGiantStudio.Text
  spec.csharp:
  - uid: TinyGiantStudio
    name: TinyGiantStudio
    href: TinyGiantStudio.html
  - name: .
  - uid: TinyGiantStudio.Text
    name: Text
    href: TinyGiantStudio.Text.html
  spec.vb:
  - uid: TinyGiantStudio
    name: TinyGiantStudio
    href: TinyGiantStudio.html
  - name: .
  - uid: TinyGiantStudio.Text
    name: Text
    href: TinyGiantStudio.Text.html
- uid: TinyGiantStudio.Text.AssetSettings.MeshExportStyle
  commentId: T:TinyGiantStudio.Text.AssetSettings.MeshExportStyle
  parent: TinyGiantStudio.Text
  href: TinyGiantStudio.Text.AssetSettings.html
  name: AssetSettings.MeshExportStyle
  nameWithType: AssetSettings.MeshExportStyle
  fullName: TinyGiantStudio.Text.AssetSettings.MeshExportStyle
  spec.csharp:
  - uid: TinyGiantStudio.Text.AssetSettings
    name: AssetSettings
    href: TinyGiantStudio.Text.AssetSettings.html
  - name: .
  - uid: TinyGiantStudio.Text.AssetSettings.MeshExportStyle
    name: MeshExportStyle
    href: TinyGiantStudio.Text.AssetSettings.MeshExportStyle.html
  spec.vb:
  - uid: TinyGiantStudio.Text.AssetSettings
    name: AssetSettings
    href: TinyGiantStudio.Text.AssetSettings.html
  - name: .
  - uid: TinyGiantStudio.Text.AssetSettings.MeshExportStyle
    name: MeshExportStyle
    href: TinyGiantStudio.Text.AssetSettings.MeshExportStyle.html
