name: Deploy All DocFX Projects to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Find and Build All DocFX Projects
        run: |
          for project in $(find . -name docfx.json -exec dirname {} \;); do
            echo "Building documentation for $project"
            docfx $project/docfx.json
            echo "Deploying documentation for $project"
            project_name=$(basename $project)
            mv $project/_site "_site/$project_name"
          done

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: documentation
          folder: _site
          clean: true
