### YamlMime:ManagedReference
items:
- uid: TinyGiantStudio.Text.AssetSettings.CharInputStyle
  commentId: T:TinyGiantStudio.Text.AssetSettings.CharInputStyle
  id: AssetSettings.CharInputStyle
  parent: TinyGiantStudio.Text
  children:
  - TinyGiantStudio.Text.AssetSettings.CharInputStyle.CharacterRange
  - TinyGiantStudio.Text.AssetSettings.CharInputStyle.CustomCharacters
  - TinyGiantStudio.Text.AssetSettings.CharInputStyle.UnicodeRange
  - TinyGiantStudio.Text.AssetSettings.CharInputStyle.UnicodeSequence
  langs:
  - csharp
  - vb
  name: AssetSettings.CharInputStyle
  nameWithType: AssetSettings.CharInputStyle
  fullName: TinyGiantStudio.Text.AssetSettings.CharInputStyle
  type: Enum
  source:
    remote:
      path: Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
      branch: main
      repo: https://github.com/Rocketshift-Studio/Trophy.git
    id: CharInputStyle
    path: ../Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
    startLine: 104
  assemblies:
  - Assembly-CSharp-firstpass
  namespace: TinyGiantStudio.Text
  syntax:
    content: public enum AssetSettings.CharInputStyle
    content.vb: Public Enum AssetSettings.CharInputStyle
- uid: TinyGiantStudio.Text.AssetSettings.CharInputStyle.CharacterRange
  commentId: F:TinyGiantStudio.Text.AssetSettings.CharInputStyle.CharacterRange
  id: CharacterRange
  parent: TinyGiantStudio.Text.AssetSettings.CharInputStyle
  langs:
  - csharp
  - vb
  name: CharacterRange
  nameWithType: AssetSettings.CharInputStyle.CharacterRange
  fullName: TinyGiantStudio.Text.AssetSettings.CharInputStyle.CharacterRange
  type: Field
  source:
    remote:
      path: Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
      branch: main
      repo: https://github.com/Rocketshift-Studio/Trophy.git
    id: CharacterRange
    path: ../Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
    startLine: 106
  assemblies:
  - Assembly-CSharp-firstpass
  namespace: TinyGiantStudio.Text
  syntax:
    content: CharacterRange = 0
    return:
      type: TinyGiantStudio.Text.AssetSettings.CharInputStyle
- uid: TinyGiantStudio.Text.AssetSettings.CharInputStyle.UnicodeRange
  commentId: F:TinyGiantStudio.Text.AssetSettings.CharInputStyle.UnicodeRange
  id: UnicodeRange
  parent: TinyGiantStudio.Text.AssetSettings.CharInputStyle
  langs:
  - csharp
  - vb
  name: UnicodeRange
  nameWithType: AssetSettings.CharInputStyle.UnicodeRange
  fullName: TinyGiantStudio.Text.AssetSettings.CharInputStyle.UnicodeRange
  type: Field
  source:
    remote:
      path: Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
      branch: main
      repo: https://github.com/Rocketshift-Studio/Trophy.git
    id: UnicodeRange
    path: ../Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
    startLine: 107
  assemblies:
  - Assembly-CSharp-firstpass
  namespace: TinyGiantStudio.Text
  syntax:
    content: UnicodeRange = 1
    return:
      type: TinyGiantStudio.Text.AssetSettings.CharInputStyle
- uid: TinyGiantStudio.Text.AssetSettings.CharInputStyle.CustomCharacters
  commentId: F:TinyGiantStudio.Text.AssetSettings.CharInputStyle.CustomCharacters
  id: CustomCharacters
  parent: TinyGiantStudio.Text.AssetSettings.CharInputStyle
  langs:
  - csharp
  - vb
  name: CustomCharacters
  nameWithType: AssetSettings.CharInputStyle.CustomCharacters
  fullName: TinyGiantStudio.Text.AssetSettings.CharInputStyle.CustomCharacters
  type: Field
  source:
    remote:
      path: Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
      branch: main
      repo: https://github.com/Rocketshift-Studio/Trophy.git
    id: CustomCharacters
    path: ../Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
    startLine: 108
  assemblies:
  - Assembly-CSharp-firstpass
  namespace: TinyGiantStudio.Text
  syntax:
    content: CustomCharacters = 2
    return:
      type: TinyGiantStudio.Text.AssetSettings.CharInputStyle
- uid: TinyGiantStudio.Text.AssetSettings.CharInputStyle.UnicodeSequence
  commentId: F:TinyGiantStudio.Text.AssetSettings.CharInputStyle.UnicodeSequence
  id: UnicodeSequence
  parent: TinyGiantStudio.Text.AssetSettings.CharInputStyle
  langs:
  - csharp
  - vb
  name: UnicodeSequence
  nameWithType: AssetSettings.CharInputStyle.UnicodeSequence
  fullName: TinyGiantStudio.Text.AssetSettings.CharInputStyle.UnicodeSequence
  type: Field
  source:
    remote:
      path: Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
      branch: main
      repo: https://github.com/Rocketshift-Studio/Trophy.git
    id: UnicodeSequence
    path: ../Assets/Plugins/Tiny Giant Studio/Modular 3D Text/Scripts/Utilities/AssetSettings.cs
    startLine: 109
  assemblies:
  - Assembly-CSharp-firstpass
  namespace: TinyGiantStudio.Text
  syntax:
    content: UnicodeSequence = 3
    return:
      type: TinyGiantStudio.Text.AssetSettings.CharInputStyle
references:
- uid: TinyGiantStudio.Text
  commentId: N:TinyGiantStudio.Text
  href: TinyGiantStudio.html
  name: TinyGiantStudio.Text
  nameWithType: TinyGiantStudio.Text
  fullName: TinyGiantStudio.Text
  spec.csharp:
  - uid: TinyGiantStudio
    name: TinyGiantStudio
    href: TinyGiantStudio.html
  - name: .
  - uid: TinyGiantStudio.Text
    name: Text
    href: TinyGiantStudio.Text.html
  spec.vb:
  - uid: TinyGiantStudio
    name: TinyGiantStudio
    href: TinyGiantStudio.html
  - name: .
  - uid: TinyGiantStudio.Text
    name: Text
    href: TinyGiantStudio.Text.html
- uid: TinyGiantStudio.Text.AssetSettings.CharInputStyle
  commentId: T:TinyGiantStudio.Text.AssetSettings.CharInputStyle
  parent: TinyGiantStudio.Text
  href: TinyGiantStudio.Text.AssetSettings.html
  name: AssetSettings.CharInputStyle
  nameWithType: AssetSettings.CharInputStyle
  fullName: TinyGiantStudio.Text.AssetSettings.CharInputStyle
  spec.csharp:
  - uid: TinyGiantStudio.Text.AssetSettings
    name: AssetSettings
    href: TinyGiantStudio.Text.AssetSettings.html
  - name: .
  - uid: TinyGiantStudio.Text.AssetSettings.CharInputStyle
    name: CharInputStyle
    href: TinyGiantStudio.Text.AssetSettings.CharInputStyle.html
  spec.vb:
  - uid: TinyGiantStudio.Text.AssetSettings
    name: AssetSettings
    href: TinyGiantStudio.Text.AssetSettings.html
  - name: .
  - uid: TinyGiantStudio.Text.AssetSettings.CharInputStyle
    name: CharInputStyle
    href: TinyGiantStudio.Text.AssetSettings.CharInputStyle.html
